# Docs: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    AUTHOR_0: "ryan-0"

phases:
  install:
    commands:
      - echo "no install commands"
  pre_build:
    commands:
      - $(aws ecr get-login --region us-west-2 --no-include-email)
  build:
    commands:
      - docker build -t 401319614350.dkr.ecr.us-west-2.amazonaws.com/dummy-golang-project:latest .
  post_build:
    commands:
      - docker push 401319614350.dkr.ecr.us-west-2.amazonaws.com/dummy-golang-project:latest
