# Docs: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    AUTHOR_0: "ryan-0"

phases:
  install:
    commands:
      - echo "no install commands"
  pre_build:
    commands:
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - datetime="$(date +'%Y%m%d%H%M')"
      - version="$(cat .version)"
      - image=401319614350.dkr.ecr.us-west-2.amazonaws.com/dummy-golang-project
  build:
    commands:
      - docker build -t ${image}:latest .
  post_build:
    commands:
      - docker tag ${image}:latest ${image}:${datetime}
      - docker tag ${image}:latest ${image}:${version}
      - docker push ${image}:latest
      - docker push ${image}:${datetime}
      - docker push ${image}:${version}

artifacts:
  files: imagedefinitions.json
