# Docs: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    AUTHOR_0: "ryan-0"

phases:
  install:
    commands:
      - echo "Install deps here"
      - env
  pre_build:
    commands:
      - echo "Log into where ever here (ecr)"
  build:
    commands:
      - echo "docker build" here
      - docker ps
  post_build:
    commands:
      - echo "docker push here"
